### ISSUE TITLE
Typo / Not doing anything

### ISSUE THREAD

**Issue by falsovsky** [cesargb/laravel-logs-rotate#17]
https://github.com/cesargb/laravel-logs-rotate/blob/master/config/rotate.php#L55

Its **Foreign** not **Foreing**

I also tried to use this library on Lumen, but you're using **config_path()** which is only specific to Laravel.

Even after implementing config_path() myself, this doesn't seem to do anything.

```
xxx@dev12:~/public_html$ php artisan rotate:logs -vvv
xxx@dev12:~/public_html$ php artisan rotate:files -vvv
xxx@dev12:~/public_html$ ls storage/logs/
lumen-2021-11-05.log  lumen-2021-12-02.log  lumen-2021-12-05.log  lumen-2021-12-08.log  lumen-2021-12-11.log
lumen-2021-11-30.log  lumen-2021-12-03.log  lumen-2021-12-06.log  lumen-2021-12-09.log  lumen-2021-12-13.log
lumen-2021-12-01.log  lumen-2021-12-04.log  lumen-2021-12-07.log  lumen-2021-12-10.log  lumen-2021-12-14.log
```

Even with full debug the artisan commands don't have any output. Should anything else happen ?

**Comment by cesargb** [comment]
Thanks for your feedback. Im preparing a new mayor version, in this new releaseI can fix the typo and fix `config_path` method.

Lumen log by default work with `daily` driver and this package only work with `single` driver. You can change in lumen the driver see: https://github.com/laravel/lumen-framework/issues/728#issuecomment-371817927

About fix to `config_path` feel free to send a PR.
