### ISSUE TITLE
No publishable resources for tag [config].

### ISSUE THREAD

**Issue by michabbb** [cesargb/laravel-logs-rotate#23]
when calling as the readme says

`artisan vendor:publish --provider="Cesargb\File\Rotate\RotateServiceProvider" --tag=config`

I get

`No publishable resources for tag [config].`

the rest seems to work 😏 

laravel 9.17.0

**Comment by cesargb** [comment]
@michabbb thanks for your feedback. I changed the namespace, but not in docs.
